---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true    
ratings:
  paths:
  - "**.py"
  - "**.md"
exclude_paths: []
- "test_AudioEndpointControl.py"