---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
    - f7b78f92a7aba5bea4ebd0fcedc0cbac
    - fdfac6dc8c9f19795bc1287a6d2bd07c
    - c9b0905c8f5b0d2ed7d9599874f079e3
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true    
ratings:
  paths:
  - "**.py"
  - "**.md"
exclude_paths: []
